# Generated by Django 3.2.3 on 2021-07-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('descripcion_cate', models.CharField(max_length=80, verbose_name='descripcion de categoria ')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usu', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo de usuario')),
                ('nombre_tipo_usu', models.CharField(max_length=80, verbose_name='nombre tipo de usuario ')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de video')),
                ('url_vi', models.CharField(max_length=40, verbose_name='url ')),
                ('nombre_vi', models.CharField(max_length=40, verbose_name='Nombre del video')),
                ('descripcion_vi', models.CharField(max_length=40, verbose_name='descripcion del video')),
                ('publicacion_vi', models.ImageField(null=True, upload_to='publicacion')),
                ('img_minatura', models.ImageField(null=True, upload_to='imagen video')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('nombre_usu', models.CharField(max_length=80, verbose_name='nombre tipo de usuario ')),
                ('apellido_usu', models.CharField(max_length=80, verbose_name='apellido de usuario ')),
                ('correo_usu', models.CharField(max_length=40, verbose_name='correo de usuario')),
                ('contra_usu', models.CharField(max_length=40, verbose_name='contraseña de usuario')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de historial')),
                ('visualizar_hi', models.ImageField(null=True, upload_to='visualizar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de favorito')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de comentario')),
                ('descripcion_com', models.CharField(max_length=80, verbose_name='descripcion de comentario ')),
                ('publicacion_com', models.ImageField(null=True, upload_to='publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video')),
            ],
        ),
    ]
