# Generated by Django 3.2.3 on 2021-07-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicacion_com',
            field=models.DateField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='visualizar_hi',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='publicacion_vi',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_vi',
            field=models.CharField(max_length=80, verbose_name='url '),
        ),
    ]
