# Generated by Django 3.2.3 on 2021-07-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_auto_20210704_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_cate',
            field=models.CharField(max_length=200, verbose_name='descripcion de categoria '),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='descripcion_com',
            field=models.CharField(max_length=200, verbose_name='descripcion de comentario '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_usu',
            field=models.CharField(max_length=200, verbose_name='apellido de usuario '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contra_usu',
            field=models.CharField(max_length=200, verbose_name='contraseña de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_usu',
            field=models.CharField(max_length=200, verbose_name='correo de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usu',
            field=models.CharField(max_length=200, verbose_name='nombre tipo de usuario '),
        ),
        migrations.AlterField(
            model_name='video',
            name='descripcion_vi',
            field=models.CharField(max_length=200, verbose_name='descripcion del video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='nombre_vi',
            field=models.CharField(max_length=200, verbose_name='Nombre del video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_vi',
            field=models.CharField(max_length=200, verbose_name='url '),
        ),
    ]
