# Generated by Django 3.2.3 on 2021-07-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_auto_20210721_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de comentario'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_favorito',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de favorito'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_historial',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de historial'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_video',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de video'),
        ),
    ]
